### ISSUE TITLE
Unstable mod

### ISSUE THREAD

**Issue by JustN00ne** [XiLaiTL/Yuushya-Townscape#13]
The mod is unstable, it completly corrupted the world. Please fix **ASAP**

**Comment by XiLaiTL** [comment]
This mod would not crash the game.
Please provide more information besides the crash logs.

**Comment by JustN00ne** [comment]
There is no crash, the world of the server of my friend got completly corrupted and he could not open it. He is completly sure that that mod was the issue

**Comment by XiLaiTL** [comment]
The yuushya modelling is 2.0.0 and yuushya townscape should be the same version which is 2.0.0 too.

**Comment by JustN00ne** [comment]
The yuushya modelling was not installed.

**Comment by XiLaiTL** [comment]
the minecraft version is 1.16.5?

**Comment by JustN00ne** [comment]
no, 1.19.2 FABRIC

**Comment by XiLaiTL** [comment]
please provide the server logs.

**Comment by JustN00ne** [comment]
i dont have access, please ask my friend on Discord (@ltechcoding)

**Comment by JustN00ne** [comment]
i'm sorry

**Comment by XiLaiTL** [comment]
Now I close the issue until you have more information

**Comment by JustN00ne** [comment]
ok
