### ISSUE TITLE
Found the corruption!

### ISSUE THREAD

**Issue by JustN00ne** [XiLaiTL/Yuushya-Townscape#14]
The mod that the Yuushya mod is having beef with is "Architecture". 21 Mods from the server depend on it. Please fix 👍

**Comment by JustN00ne** [comment]
yes, but that mod also corrupted that server

**Comment by XiLaiTL** [comment]
It means that the server could not support Architectury?

**Comment by JustN00ne** [comment]
No, The server supports architectury because its 1.19.2 Fabric. It is hosted on a real machine in a controlled place. Everything is working

**Comment by XiLaiTL** [comment]
I guess that the version of architectury is too high that yuushya could not use it?

**Comment by JustN00ne** [comment]
sadly, all other mods require the newest version

**Comment by JustN00ne** [comment]
is there a possibility of updating the architectury injection?
