### ISSUE TITLE
Big lag spikes

### ISSUE THREAD

**Issue by broz21** [XiLaiTL/Yuushya-Townscape#16]
When I added this mod to my world, lag spikes occured more frequently than when this mod wasn't installed. I don't know if the problem is JEI being overloaded with item pages (213, to be exact) or is it's something else. (forge, minecraft 1.20.1, Yuushya Townscape 2.0.0, mod list can be sent if needed)

**Comment by LucaBarbaLata** [comment]
hey. i have the same problem. did you fixed this or?
i want to resolve this somehow and maybe you have a fix
