### ISSUE TITLE
[Question] regarding resourcepack

### ISSUE THREAD

**Issue by kusayu** [XiLaiTL/Yuushya-Townscape#18]
Do I really need to install the resourcepack for yuushya fabric 1.20.1?

can I just install the mods without the resourcepack? because I want the vanilla+ feels to my modpack, and by using your resourcepack I notice that every item model is changed for an example: emerald, flint and steel, and more.

or does there any resourcepack that not change the vanilla items and menu?

thank you

**Comment by broz21** [comment]
Basically the ressource pack complements the mod(some textures from the mod may look non-vanilla), but it's not required to make the mod work.

**Comment by XiLaiTL** [comment]
Some block will be black-and-purple because we had not used the correct texture lol

**Comment by kusayu** [comment]
Thank you for the reply and clarification, then I will use the mod without the texturepack for now, I hope that someday the black and purple will be fixed :D
