### ISSUE TITLE
Block Entities weird behavior

### ISSUE THREAD

**Issue by broz21** [XiLaiTL/Yuushya-Townscape#19]
I found that when you create a block entity in a chunk, every create mod blocks/framed block mod blocks in that specific chunk stop working correctly. For example, you can't use copycat blocks in the same chunk as a block entity from Yuushya townscapes. (forge, Yuushya townscapes 2.0.0, mod list can be sent)

**Comment by XiLaiTL** [comment]
fix it. use 2.2.0
