### ISSUE TITLE
Yuushya/Structurize compatability.

### ISSUE THREAD

**Issue by Moobien** [XiLaiTL/Yuushya-Townscape#2]
Hey there, just discovered your deco mod and noticed your blocks don't like rotating/rotate weirdly after being scanned by structurize.

From what I am seeing, your blocks maintain their original facings noo matter how you rotate them. as exampled by the screenshots.

Great would be if your blocks could be rotated correctly via structurize.

https://imgur.com/a/zUpouvn

**Comment by kedamono** [comment]
I've also tried to use the Structurize mod to rotate Yuushya items, like the Food Truck, or the street light, and they don't rotate. I can use World Edit to make them rotate, but World Edit is harder to work with.

**Comment by XiLaiTL** [comment]
Thanks for reporting this bug.

**Comment by XiLaiTL** [comment]
fix it. use 2.2.0
