### ISSUE TITLE
[FORGE] [1.20.1] [MODELING] Doors behave weird near entity blocks

### ISSUE THREAD

**Issue by A00826925** [XiLaiTL/Yuushya-Townscape#7]
![2023-09-16 21_32_55-Minecraft Forge_ 1 20 1 - Singleplayer](https://github.com/XiLaiTL/Yuushya-Townscape/assets/73501467/bb232cde-9015-4984-af25-abba22d8b465)

Door wont properly open near an entity block, might affect other items with states.

**Comment by A00826925** [comment]
it permanently makes this an issue in the surrounding blocks, even after removing the entity block

**Comment by XiLaiTL** [comment]
fix it. use 2.2.0.
It is related to architectury loom
