### ISSUE TITLE
[QUILT/FABRIC] [1.20.1] Server crash on start

### ISSUE THREAD

**Issue by V-lpen** [XiLaiTL/Yuushya-Townscape#8]
I can confirm that it worked on the client, but the moment I try to start the server, it starts up then crashes after 60 seconds.
https://mcpaste.io/5a49c6161366351f

**Comment by Dweblenod** [comment]
Can confirm a crash originating from `CollisionFileReader` on Forge 1.20.1. It was not the first time the server has gone through a reset but it may be the first time it reset while blocks from this mod were placed down

**Comment by XiLaiTL** [comment]
Sorry for forgetting replying.
You need to rollback yuushya to 2.0.0 until I provide the 2.1.1 version yuushya modelling.
The mod had bug in versions differing so you should let two mod in the same version.
