### ISSUE TITLE
[QUILT/FABRIC] [1.19.2] Block collisions don't align properly with models

### ISSUE THREAD

**Issue by tehquacken** [XiLaiTL/Yuushya-Townscape#9]
Some block models don't seem to align properly with their hitbox. Additionally, touching the areas without proper collision gets the player stuck. Unsure if it is an incompatibility with another mod.

![image](https://github.com/XiLaiTL/Yuushya-Townscape/assets/151288513/fd31b741-9202-41e6-a08b-7228bfa24793)
![image](https://github.com/XiLaiTL/Yuushya-Townscape/assets/151288513/62ed8642-3eae-40b4-80fd-1456a2d53b25)

**Comment by tehquacken** [comment]
It's an incompatiblity

**Comment by ki639637** [comment]
Hi. Do you know what mod was having the incompatibility? I'm having the same issue

**Comment by tehquacken** [comment]
It's an incompatibility with the quilt server
